import React from "react";
import About from "../components/About";
import { Metadata } from "next";

type Props = {};
export const metadata: Metadata = {
  title: "Al Fatah Quran Academy | About us",
  description: "Generated by create next app",
};
const Page = (props: Props) => {
  return (
    <>
      <About />
    </>
  );
};

export default Page;
