import React from "react";
import Registration from "../components/Registration";
import { Metadata } from "next";

type Props = {};
export const metadata: Metadata = {
  title: "Al Fatah Quran Academy | Register",
  description: "Generated by create next app",
};

const Page = (props: Props) => {
  return (
    <>
      <Registration />
    </>
  );
};

export default Page;
