import React from "react";
import Pricing from "../components/Pricing";
import { Metadata } from "next";

type Props = {};
export const metadata: Metadata = {
  title: "Al Fatah Quran Academy | Plan & Pricing",
  description: "Generated by create next app",
};

const Page = (props: Props) => {
  return (
    <>
      <Pricing />
    </>
  );
};

export default Page;
