import React from "react";
import Services from "../components/Services";
import { Metadata } from "next";

type Props = {};
export const metadata: Metadata = {
  title: "Al Fatah Quran Academy | Services",
  description: "Generated by create next app",
};
const Page = (props: Props) => {
  return (
    <>
      <Services />
    </>
  );
};

export default Page;
